title: 'Common Settings'
data:
  loader: image/Loader.svg
  description: |-
    BigMentor uses cookies to enhance your browsing experience, analyze site usage, and personalize content.
     Cookies help us improve functionality and tailor our services to your preferences. By continuing to use
     our website, you consent to our cookie policy. For more details, please review our <u
    class="decoration-vividblue-400">Privacy Policy.</u>
  button_1:
    -
      id: mawddf0c
      text: 'Manage my preferences'
      link: 'javascript:;'
  button_2:
    -
      id: mawde6yk
      text: 'Accept All Cookies'
      link: 'javascript:;'
      icon: image/redirect.svg
