tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: loader
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: false
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: Loader
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: 'Cookies Section'
        fields:
          -
            handle: description
            field:
              antlers: false
              type: textarea
              display: Description
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: button_1
            field:
              fields:
                -
                  handle: text
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: Text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: link
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: Link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: add_class
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: 'Add Class'
                    instructions: 'Separate multiple classes with a "space"'
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
              mode: table
              max_rows: 1
              reorderable: true
              fullscreen: true
              type: grid
              display: 'Button 1'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: button_2
            field:
              fields:
                -
                  handle: text
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: Text
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: link
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: link
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: icon
                  field:
                    max_files: 1
                    mode: list
                    container: assets
                    restrict: false
                    allow_uploads: true
                    show_filename: true
                    show_set_alt: true
                    type: assets
                    display: Icon
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
                -
                  handle: add_class
                  field:
                    input_type: text
                    antlers: false
                    type: text
                    display: 'Add Class'
                    instructions: 'Separate multiple classes with a "space"'
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
              mode: table
              max_rows: 1
              reorderable: true
              fullscreen: true
              type: grid
              display: 'Button 2'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
