title: 'Common Settings'
fields:
  -
    handle: social_media
    field:
      fields:
        -
          handle: link
          field:
            input_type: text
            antlers: false
            type: text
            display: link
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
        -
          handle: icon_class
          field:
            input_type: text
            antlers: false
            type: text
            display: 'Icon class'
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
        -
          handle: icon
          field:
            max_files: 1
            mode: list
            container: assets
            restrict: false
            allow_uploads: true
            show_filename: true
            show_set_alt: true
            type: assets
            display: Icon
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
      mode: table
      reorderable: true
      fullscreen: true
      type: grid
      display: 'Social Media'
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
      max_rows: 10
  -
    handle: button
    field:
      fields:
        -
          handle: text
          field:
            input_type: text
            antlers: false
            type: text
            display: text
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
        -
          handle: link
          field:
            input_type: text
            antlers: false
            type: text
            display: link
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
        -
          handle: icon
          field:
            max_files: 1
            mode: list
            container: assets
            restrict: false
            allow_uploads: true
            show_filename: true
            show_set_alt: true
            type: assets
            display: icon
            listable: hidden
            instructions_position: above
            visibility: visible
            replicator_preview: true
            hide_display: false
      mode: table
      max_rows: 1
      reorderable: true
      fullscreen: true
      type: grid
      display: button
      listable: hidden
      instructions_position: above
      visibility: visible
      replicator_preview: true
      hide_display: false
